spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/manager_house?useSSL=false&characterEncoding=UTF-8
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
  jackson:
    serialization:
      fail-on-empty-beans: true
      indent-output: true
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    encoding:
      enabled: true


server:
  context-path: /house
  port: 8080

#微信公众号
wechat:
  appId: wx6facec47c2fca33b
  secret: 2dea3ec6a647f1dd73a0e0e87f0524ef

#微信小程序
wechatmini:
    appId: wx007de3f944b85ec6
    secret: 32d982af1871c587dddd7caa92d9e89e

urlpath: https://www.embracex.com/gcsweixin/house/login/wechat

#imagepath: /home/cx/jAVA/shop/image/
#
#imageurl: https://www.embracex.com/gcsweixin/shop/image/
imagepath: /home/cx/JAVA/images/

imageurl: https://www.embracex.com/gcsweixin/house/image/

videopath: /home/cx/JAVA/videos/


