spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/manager_house?useSSL=false&chatacer
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
  jackson:
    serialization:
      fail-on-empty-beans: true
      indent-output: true
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
    encoding:
      enabled: true


server:
  context-path: /house
  port: 8080


wechat:
#    appId: wx80684f34298ce2d7
#    secret: a73ba9a5f6d09d9e7d698ab8ee213b78
#    token: 24c12d745036aff81725d2e82b5a4dba
#    aesKey: bo3ruxQphpvh2j7LuYWFFOWboCf0WNq4D2Pgnpe4MdU
#    mchId: 10024153
#    mchKey: braggadocio345l6ackadaisicalness
#    keyPath: /home/cx/jAVA/shop/src/main/resources/static/h5.p12
#    notifyUrl: https://www.embracex.com/gcsweixin/shop/pay/notify
    appId: wx80684f34298ce2d7
    secret: a73ba9a5f6d09d9e7d698ab8ee213b78
    client:
       clientId: wx80684f34298ce2d7
       clientSecret: a73ba9a5f6d09d9e7d698ab8ee213b78
       accessTokenUri: https://api.weixin.qq.com/sns/jscode2session
#  获取code
#  userAuthorizationUri: https://open.weixin.qq.com/connect/oauth2/authorize
       authenticationScheme: query
       clientAuthenticationScheme: form
       scope: snsapi_userinfo
    resource:
      userInfoUri: https://api.weixin.qq.com/sns/userinfo?lang=zh_CN&openid=$openid$
    accpetcode_url: https://www.embracex.com/gcsweixin/shop/login/wechat

urlpath: https://www.embracex.com/gcsweixin/house/login/wechat

#imagepath: /home/cx/jAVA/shop/image/
#
#imageurl: https://www.embracex.com/gcsweixin/shop/image/
imagepath: /home/cx/jAVA/images/

imageurl: /house/image/

